### ISSUE TITLE
suggestion: have a check box that says spawn inside structure on world creation

### ISSUE THREAD

**Issue by Thunderrock424242** [GregoryAM-SP/ReStructure-MCreator-Plugin#7]
this would be a helpful tool if you are wanting to spawn inside your structure as a starting point. if this is enabled this structure will only be generated once. 

there are prosedures to place structures but maybe you can allow this tool to get the player to spawn inside that would be a amazing feature.

**Comment by Gregory-AM** [comment]
Sadly, this feature is currently impossible to do with Data Pack Development.

It would require Java Code to complete this request.

Closing due to incompatibility with the plugins function.
